repos:
-   repo: https://github.com/ambv/black
    rev: 24.8.0
    hooks:
    - id: black
      language_version: python3.12
      stages: [commit]
-   repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
    - id: flake8
      stages: [commit]
-   repo: https://github.com/econchick/interrogate
    rev: 1.7.0
    hooks:
    - id: interrogate
      args: [--vv, -i, --fail-under=80]
-   repo: local
    hooks:
      - id: requirements
        name: requirements
        entry: bash -c '.venv/bin/pip freeze > requirements.txt; git add requirements.txt'
        language: system
        pass_filenames: false
        stages: [commit]
-   repo: local
    hooks:
    - id: pytest
      name: pytest
      language: system
      entry: bash -c '.venv/bin/pytest -v -s'
      always_run: true
      pass_filenames: false
      stages: [commit]
