name: Integração Contínua

on:
  pull_request:
    branches:
      - main

jobs:
  executa_black:
    runs-on: ubuntu-latest
    steps:
      - name: Realiza o checkout
        uses: actions/checkout@v2

      - name: Instala o Python 3.12
        uses: actions/setup-python@v2

      - name: Instala as dependências
        run: |
          python -m pip install --upgrade pip
          pip install black

      - name: Excuta o black
        run: black . --check

#  executa_pylint:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Realiza o checkout
#        uses: actions/checkout@v2
#
#      - name: Instala o Python 3.12
#        uses: actions/setup-python@v2
#
#      - name: Instala as dependências
#        run: |
#          python -m pip install --upgrade pip
#          pip install -r requirements.txt
#      - name: Analysing the code with pylint
#        run: |
#          pylint $(git ls-files '*.py')

  executa_unittest:
    runs-on: ubuntu-latest
    steps:
      - name: Realiza o checkout
        uses: actions/checkout@v2

      - name: Instala o Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.6

      - name: Instala as dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executa os testes unitários
        run: pytest